### ISSUE TITLE
docker hub litecoin-core vs litecoind

### ISSUE THREAD

**Issue by willgu903** [uphold/docker-litecoin-core#12]
Hi

first of all, I feel grateful for the docker images you guys provide for litecoin

I noticed that you maintain 2 docker image repos, litecoin-core and litecoind respectively. Looks that with everything else the same, litcoin-core is more up-to-date with the version 0.15, while litecoind is at version 0.14, even though the info page for litecoind says it's at 0.15.

Curious what's the plan with these 2 repos? do you guys plan to keep one and retire the other?

thanks.

**Comment by ruimarinho** [comment]
`litecoin-core` will remain the up-to-date version due to the upstream name rebrand.
