### ISSUE TITLE
Docker Hub repository errantly lacks the tag "0.16.0"

### ISSUE THREAD

**Issue by JamesCropcho** [uphold/docker-litecoin-core#16]
Hello,

Thanks for a wonderful tool.

Today I tried
```
$ docker pull uphold/litecoin-core:0.16.0
Error response from daemon: manifest for uphold/litecoin-core:0.16.0 not found
```

I then noticed that at
> https://hub.docker.com/r/uphold/litecoin-core/tags/

There is no such tag, despite it being listed in the documentation (https://github.com/uphold/docker-litecoin-core#tags)

What do you think?

James

**Comment by JamesCropcho** [comment]
Hello all,

I tried again just now:

```
$ sudo docker pull uphold/litecoin-core:0.16.0
Error response from daemon: manifest for uphold/litecoin-core:0.16.0 not found
```

(The tag is still listed at https://github.com/uphold/docker-litecoin-core#tags).

How could we remedy this?


James

**Comment by finsterdexter** [comment]
0.16.0 has a major security bug. See: https://www.reddit.com/r/Bitcoin/comments/9hkoo6/new_info_escalates_importance_upgrading_to_0163/

Your best bet is probably to just fork this repo and set up your own Dockerfile that pulls in 0.16.3.

**Comment by ruimarinho** [comment]
All versions are being updated on Docker Hub. Thanks!
