### ISSUE TITLE
Litecoin binary sha256sum not verified on download

### ISSUE THREAD

**Issue by DavidHoude** [uphold/docker-litecoin-core#25]
Opening new issue due to some confusion in the prior issue that I recently closed. This is a follow up with hopefully a more concise description of the issue and resolution.

In the Dockerfile for the litecoin-0.17 daemon, the Litecoin maintainers public key is downloaded and added to GPG, the tarball is downloaded, and then the checksum file is verified against the public key. There is no verification of the tarball's sha256sum() to verify that the download has not been tampered with. 

I have added a line to pull a sha256sum of the tarball, and compare it with the checksums listed in the sig file to ensure file integrity. 

Here is a sample of the current Dockerfile's logic, and an example of how the binary can be modified and not detected with the current build process:

```
root@dee5ed122b3c:/# LITECOIN_VERSION=0.17.1
root@dee5ed122b3c:/# curl -O https://download.litecoin.org/litecoin-${LITECOIN_VERSION}/linux/litecoin-${LITECOIN_VERSION}-x86_64-linux-gnu.tar.gz
root@dee5ed122b3c:/# curl 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xFE3348877809386C' | gpg --import
... truncated ...

root@dee5ed122b3c:/# sha256sum litecoin-0.17.1-x86_64-linux-gnu.tar.gz
9cab11ba75ea4fb64474d4fea5c5b6851f9a25fe9b1d4f7fc9c12b9f190fed07  litecoin-0.17.1-x86_64-linux-gnu.tar.gz

root@dee5ed122b3c:/# curl https://download.litecoin.org/litecoin-${LITECOIN_VERSION}/linux/litecoin-${LITECOIN_VERSION}-linux-signatures.asc | gpg --verify - && echo "verified" || "unverified"
... truncated ...
verified

root@dee5ed122b3c:/# curl https://download.litecoin.org/litecoin-${LITECOIN_VERSION}/linux/litecoin-${LITECOIN_VERSION}-linux-signatures.asc | grep $(sha256sum litecoin-${LITECOIN_VERSION}-x86_64-linux-gnu.tar.gz | awk '{ print $1 }') && echo "verified" || echo "unverified"
... truncated ...
verified

root@dee5ed122b3c:/# echo "random string" >> litecoin-0.17.1-x86_64-linux-gnu.tar.gz

root@dee5ed122b3c:/# sha256sum litecoin-0.17.1-x86_64-linux-gnu.tar.gz
da3ad3a7565a4b4fb415e67ef119c54cc14f4d3c9490a0be85817848c8fba075  litecoin-0.17.1-x86_64-linux-gnu.tar.gz

root@dee5ed122b3c:/# curl https://download.litecoin.org/litecoin-${LITECOIN_VERSION}/linux/litecoin-${LITECOIN_VERSION}-linux-signatures.asc | gpg --verify - && echo "verified" || "unverified"
... truncated ...
verified

root@dee5ed122b3c:/# curl https://download.litecoin.org/litecoin-${LITECOIN_VERSION}/linux/litecoin-${LITECOIN_VERSION}-linux-signatures.asc | grep $(sha256sum litecoin-${LITECOIN_VERSION}-x86_64-linux-gnu.tar.gz | awk '{ print $1 }') && echo "verified" || echo "unverified"
... truncated ...
unverified

```

As you can see, the current operation will complete successfully, even with a bad checksum.  I am submitting a PR that should add the additional step of checking the actual sha256sum and comparing it to the checksums listed in the verified sig file.

**Comment by ruimarinho** [comment]
Fixed in https://github.com/uphold/docker-litecoin-core/commit/9738ccf4c5d7daeca5c05a9582fcac2df9a091bd.
